site_name: Skynet Platform Documentation
site_description: Example MkDocs Material site demonstrating GitOps with Argo CD
site_author: Skynet Platform Team
site_url: https://skynet-docs.example.com
repo_name: cyberdine-skynet/skynet-example-app
repo_url: https://github.com/cyberdine-skynet/skynet-example-app
edit_uri: edit/main/docs/
theme:
  name: material
  palette:
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - content.code.copy
    - content.action.edit
    - content.action.view
  icon:
    repo: fontawesome/brands/github
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
nav:
  - Home: index.md
  - GitOps:
      - Overview: gitops/index.md
      - Argo CD: gitops/argocd.md
      - Workflows: gitops/workflows.md
  - Infrastructure:
      - Kubernetes: infrastructure/kubernetes.md
      - Terraform: infrastructure/terraform.md
      - Talos: infrastructure/talos.md
  - Examples:
      - This App: examples/this-app.md
      - Deployment: examples/deployment.md
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/cyberdine-skynet
  version:
    provider: mike
